from django.contrib import admin
from restaurant.models import * 

admin.site.register(Food)
admin.site.register(Drink)
admin.site.register(Order)
admin.site.register(Category)
admin.site.register(Page)
admin.site.register(UserProfile)
admin.site.register(Order_food)
admin.site.register(Order_drink)
admin.site.register(Restaurant)
admin.site.register(Employee)
admin.site.register(Table)
admin.site.register(Ingredient)
admin.site.register(Post)
admin.site.register(Message)
admin.site.register(MyFriend)
admin.site.register(FriendInvitation)
admin.site.register(MsgNotification)
admin.site.register(Shop)
admin.site.register(Product)
admin.site.register(BusinessPost)
admin.site.register(Comment)
admin.site.register(CommentOfComment)
admin.site.register(RestaurantReview)
admin.site.register(FoodReview)
