from django.conf.urls import patterns, url
from django.conf import settings
from django.conf.urls.static import static
from restaurant import views


urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^cat/(?P<category_name_url>\w+)', views.category, name='category'),
	url(r'^cat_like/$', views.like_category, name='cat_like'),
	url(r'^cat_add/$', views.add_category, name='add_category'),
	url(r'^page_add/(?P<category_name_url>\w+)', views.add_page, name='add_page'),
	url(r'^register/$', views.register, name='register'),
	url(r'^login/$', views.user_login, name='login'),
	url(r'restricted', views.restricted, name='restricted'),
	url(r'^logout/$', views.user_logout, name='logout'),
	url(r'^store/$', views.user_store, name='store'),
	url(r'^test/$', views.user_test, name='test'),
	url(r'^free/$', views.free, name='free'),
	url(r'^(?P<restaurant_url_selected>\w+)/restaurant_home/', views.restaurant_home, name='restaurant_home'),
	url(r'^(?P<restaurant_url_selected>\w+)/restaurant_services/$', views.restaurant_services, name='restaurant_services'),
	url(r'^(?P<restaurant_url_selected>\w+)/restaurant_kitchen/$', views.restaurant_kitchen, name='restaurant_kitchen'),
	url(r'^(?P<restaurant_url_selected>\w+)/restaurant_stock/$', views.restaurant_stock, name='restaurant_stock'),
	url(r'^(?P<restaurant_url_selected>\w+)/restaurant_employee/$', views.restaurant_employee, name='restaurant_employee'),
	url(r'^(?P<restaurant_url_selected>\w+)/restaurant_statistic/$', views.restaurant_statistic, name='restaurant_statistic'),
	url(r'^create_restaurant/$', views.create_restaurant, name='create_restaurant'),
	url(r'^(?P<restaurant_url_selected>\w+)/delete_restaurant/$', views.delete_restaurant, name='delete_restaurant'),
	url(r'^send_order/$', views.send_order),
	url(r'^create_new_menu/$', views.create_new_menu, name='create_new_menu'),
	url(r'^delete_food/$', views.delete_food),
	url(r'^delete_post/$', views.delete_post),
	url(r'^(?P<restaurant_url_selected>\w+)/get_food_menu/$', views.get_food_menu, name='get_food_menu'),
	url(r'^get_order/$', views.get_order, name='get_order'),
	url(r'^get_order_kitchen/$', views.get_order_kitchen, name='get_order_kitchen'),
	url(r'^cook_food/$', views.cook_food, name='cook_food'),
	url(r'^update_ingredient_amount/$', views.update_ingredient_amount),
	url(r'^add_ingredient/$', views.add_ingredient),
	url(r'^get_ingredient/$', views.get_ingredient),
	url(r'^feed/$', views.feed),
	url(r'^chat/$', views.chat),
	url(r'^admin/(?P<restaurant_name>\w+)/$', views.admin),
	url(r'^(?P<name>\w+)/service/$', views.service),
	url(r'^(?P<name>\w+)/kitchen/$', views.kitchen),
	url(r'^business/$', views.business),
	url(r'^business/(?P<name>\w+)/$', views.business_home),
	url(r'^business/(?P<name>\w+)/menu$', views.business_menu),
	url(r'^business/(?P<name>\w+)/about$', views.business_about),
	url(r'^business/(?P<name>\w+)/follower$', views.business_follower),
	url(r'^business/(?P<name>\w+)/hungry$', views.business_hungry),
	url(r'^business/(?P<name>\w+)/checkin$', views.business_checkin),
	url(r'^new_business/(?P<type>\w+)/$', views.new_business),
	url(r'^hangout/$', views.hangout),
	url(r'^hangout/(?P<name>\w+)/$', views.hangout_home),
	url(r'^hangout/(?P<name>\w+)/menu/$', views.hangout_menu),
	url(r'^imgs/(.*)$', 'django.views.static.serve', {'document_root' : settings.MEDIA_ROOT}),
	url(r'^change_picture/$', views.change_picture),
	url(r'^profile/(?P<username>\w+)/', views.profile, name='profile'),
	url(r'^add_friend/', views.add_friend),
	url(r'^accept_friend/', views.accept_friend),
	url(r'^get_old_message/', views.get_old_message),
	url(r'^send_message/', views.send_message),
	url(r'^get_msg_notification/', views.get_msg_notification),
	url(r'^get_new_message/', views.get_new_message),
	url(r'^send_comment/', views.send_comment),
	url(r'^get_old_comment/', views.get_old_comment),
	url(r'^get_userprofile/', views.get_userprofile),
	url(r'^get_friends/', views.get_friends),
	url(r'^get_business/', views.get_business),
	url(r'^get_restaurant/', views.get_business),
	url(r'^get_restaurant2/', views.get_restaurant),
	url(r'^get_menu/', views.get_menu),
	url(r'^get_new_menu/', views.get_new_menu),
	url(r'^get_product/', views.get_product),
	url(r'^get_restaurant_table/', views.get_restaurant_table),
	url(r'^get_new_product/', views.get_new_product),
	url(r'^upload/(?P<name>\w+)/$', views.upload),
	url(r'^upload_post/(?P<name>\w+)/$', views.upload_post),
	url(r'^get_business_post/$', views.get_business_post),
	url(r'^get_new_business_post/$', views.get_new_business_post),
	url(r'^comment/$', views.comment),
	url(r'^commentRestaurantPost/$', views.commentRestaurantPost),
	url(r'^get_restaurant_post_comment/$', views.get_restaurant_post_comment),
	url(r'^like/$', views.like),
	url(r'^set_cooking/$', views.set_cooking),
	url(r'^set_finish/$', views.set_finish),
	url(r'^set_order_finish/$', views.set_order_finish),
	url(r'^get_order_kitchen2/$', views.get_order_kitchen2),
	url(r'^create_restaurant_table/$', views.create_restaurant_table),
	url(r'^pending_foods/$', views.pending_foods),
	url(r'^pay/$', views.pay),
	url(r'^first/$', views.first),
	url(r'^get_food_comment/$', views.get_food_comment),
	url(r'^follow/$', views.follow),
	url(r'^get_following_restaurant/$', views.get_following_restaurant),
	


)
